### PR TITLE
Fix isPrime method.

### PR DESCRIPTION
**Pull request by ahanmal**
If number is divisible, it should return NO.

Reference #94.

### CODE REVIEW

**Comment by EvgenyKarkan** [comment]
Merged.

**Comment by ahanmal** [comment]
Thanks.

**Comment by EvgenyKarkan** [comment]
And you :)

**Comment by stanislaw** [comment]
@EvgenyKarkan , @ahanmal 

I believe this error was introduced during "bulk upload" process when EKAlgorithms was in process of creation and setup. I think it would be great if in future we could add more test coverage to prevent things like this one in a future.

**Comment by ahanmal** [comment]
@stanislaw Adding some test coverage doesn't sound like a bad idea. I will add some. I remember adding this method to the repo when it was young, and then I guess during refactoring, it broke.

Expect a PR soon.

**Comment by ahanmal** [comment]
See #96

**Pull request merged**
